version: 0.2

phases:
  install:
    commands:
      - echo Installing phase
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Testing code at `date`
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - package.json