logging:
  microservice: REFORM_SERVICE_NAME
  team: REFORM_TEAM
  environment: REFORM_ENVIRONMENT
#healthcheck:
#  environment: PACKAGES_ENVIRONMENT
#  project: PACKAGES_PROJECT
#  name: PACKAGES_NAME
#  version: PACKAGES_VERSION